language: node_js
node_js:
  - "15"

jobs:
  include:
    - stage: "Linting and Unit Tests"
      name: "Linting"
      install:
        - yarn install
      script: yarn lint
    - name: "Unit Tests"
      install:
        - yarn install
      script: yarn test
      after_success:
        - yarn coverage
